---
- hosts: all
  become: true

  vars:
    default_user_group: plasma-users

  tasks:
    - name: Add default user group
      group:
        name: "{{ default_user_group }}"
        state: present

    - name: Add groups
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ plasma_groups }}"

    - name: Add users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups if item.groups is defined else default_user_group }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        home: "{{ home_path if home_path is defined else '/home' }}/{{ item.name }}"
        update_password: on_create
      loop: "{{ users }}"

    - name: Set user quota
      shell: |
        setquota -u {{ item.name }} \
        {{ item.quota.soft if item.quota.soft is defined else quota.soft }} \
        {{ item.quota.hard if item.quota.hard is defined else quota.hard }} \
        0 0 {{ quota_device_path }}
      when: quota is defined or item.quota is defined
      loop: "{{ users }}"

    - name: Reset the list of admin users to avoid duplicates
      shell: tljh-config unset users.admin
      register: admins
      failed_when: admins.rc > 1

    - name: Add admin users
      shell: tljh-config add-item users.admin {{ item.name }}
      when: item.admin is defined and item.admin
      loop: "{{ users }}"

    - name: Reload the hub
      shell: "tljh-config reload hub"
